<a href="https://colab.research.google.com/github/IagoGarciaSuarez/MUII_DSI/blob/main/Clustering_DSI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!rm *.csv
!wget https://raw.githubusercontent.com/IagoGarciaSuarez/MUII_DSI/main/men-ihf-2021.csv

rm: cannot remove '*.csv': No such file or directory
--2024-02-15 15:26:54--  https://raw.githubusercontent.com/IagoGarciaSuarez/MUII_DSI/main/men-ihf-2021.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 350830 (343K) [text/plain]
Saving to: ‘men-ihf-2021.csv’

men-ihf-2021.csv    100%[===================>] 342.61K  --.-KB/s    in 0.1s

2024-02-15 15:26:55 (2.72 MB/s) - ‘men-ihf-2021.csv’ saved [350830/350830]

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive

In [ ]:
men_ihf_original = pd.read_csv("men-ihf-2021.csv", sep='\t')
men_ihf_original

,Phase,Match No.,Match,Team,No.,Name,7mGoals,7mMissed,6mGoals,6mMissed,...,YC,RC,BC,2Min,AS,ST,BS,Time,scoring,prod100
0,Group Phase,1.0,EGY-CHI,EGY,5.0,OMAR Yahia,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,2.0,4.0,1.0,0.0,"47,58333333","1,75","3,677758319"
1,Group Phase,1.0,EGY-CHI,EGY,11.0,MOAMEN Ahmed,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"24,03333333","-0,4","-1,664355062"
2,Group Phase,1.0,EGY-CHI,EGY,15.0,HESHAM Ahmed,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,"20,55","-2,25","-10,94890511"
3,Group Phase,1.0,EGY-CHI,EGY,24.0,ELMASRY Ibrahim,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,2.0,0.0,"29,8","2,8","9,395973154"
4,Group Phase,1.0,EGY-CHI,EGY,25.0,NAWAR Wisam,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"11,25",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067,Main Round,108.0,DEN-SWE,SWE,28.0,EDVARDSSON Jonathan,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
3068,Main Round,108.0,DEN-SWE,SWE,33.0,SANDELL Lukas,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"20,31666667","0,1","0,492206727"
3069,Main Round,108.0,DEN-SWE,SWE,62.0,CHRINTZ Valter,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"9,35",1,"10,69518717"
3070,Main Round,108.0,DEN-SWE,SWE,66.0,LINDSKOG Anton,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
3071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.
Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [28]:
men_ihf = men_ihf_original.drop(['Phase', 'Match No.', 'No.', 'Match', 'Team', 'Name', 'YC', 'BC', 'scoring'], axis=1)
men_ihf.head()

,7mGoals,7mMissed,6mGoals,6mMissed,WingGoals,WingMissed,BTGoals,BTMissed,FBGoals,FBMissed,...,9mGoals,9mMissed,TF,RC,2Min,AS,ST,BS,Time,prod100
0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,3.0,3.0,0.0,2.0,4.0,1.0,0.0,"47,58333333","3,677758319"
1,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"24,03333333","-1,664355062"
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,"20,55","-10,94890511"
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,"29,8","9,395973154"
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"11,25",0

In [30]:
men_ihf.dtypes

7mGoals       float64
7mMissed      float64
6mGoals       float64
6mMissed      float64
WingGoals     float64
WingMissed    float64
BTGoals       float64
BTMissed      float64
FBGoals       float64
FBMissed      float64
EGGoals       float64
EGMissed      float64
9mGoals       float64
9mMissed      float64
TF            float64
RC            float64
2Min          float64
AS            float64
ST            float64
BS            float64
Time           object
prod100        object
dtype: object

In [ ]:
men_ihf.describe()

In [38]:
men_ihf['Time'] = men_ihf['Time'].str.replace(',', '.')
men_ihf['Time'] = men_ihf['Time'].astype(float)

AttributeError: Can only use .str accessor with string values!

In [39]:
men_ihf['prod100'] = men_ihf['prod100'].str.replace(',', '.')
men_ihf['prod100'] = men_ihf['prod100'].astype(float)

In [41]:
men_ihf.dtypes

7mGoals       float64
7mMissed      float64
6mGoals       float64
6mMissed      float64
WingGoals     float64
WingMissed    float64
BTGoals       float64
BTMissed      float64
FBGoals       float64
FBMissed      float64
EGGoals       float64
EGMissed      float64
9mGoals       float64
9mMissed      float64
TF            float64
RC            float64
2Min          float64
AS            float64
ST            float64
BS            float64
Time          float64
prod100       float64
dtype: object

In [43]:
men_ihf

,7mGoals,7mMissed,6mGoals,6mMissed,WingGoals,WingMissed,BTGoals,BTMissed,FBGoals,FBMissed,...,9mGoals,9mMissed,TF,RC,2Min,AS,ST,BS,Time,prod100
0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,3.0,3.0,0.0,2.0,4.0,1.0,0.0,47.583333,3.677758
1,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.033333,-1.664355
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,20.550000,-10.948905
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,29.800000,9.395973
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.250000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN
3068,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,20.316667,0.492207
3069,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.350000,10.695187
3070,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,NaN
3071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
df_norm = min_max_scaler.fit_transform(men_ihf)
df_norm

ValueError: Input X contains infinity or a value too large for dtype('float64').